steps:
  # Step 1: Zip the application source code
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y zip
        zip -r /workspace/my-app.zip .

  # Step 2: Upload the zip to Cloud Storage
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - 'cp'
      - '/workspace/my-app.zip'
      - 'gs://vamsi-artifact-bucket/my-app.zip'

  # Step 3: Delete existing VM if it exists
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Deleting VM if it exists..."
        gcloud compute instances delete my-vm-instance --zone=asia-east1-b --quiet || true

  # Step 4: Create new VM
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - compute
      - instances
      - create
      - my-vm-instance
      - --zone=asia-east1-b
      - --machine-type=e2-micro
      - --image-family=debian-11
      - --image-project=debian-cloud
      - --boot-disk-size=10GB
      - --tags=http-server,https-server
      - --scopes=https://www.googleapis.com/auth/cloud-platform
      - --service-account=1064351983714-compute@developer.gserviceaccount.com
      - --project=enhub-cloud-interns

  # Step 5: Install dependencies on VM
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - compute
      - ssh
      - sajja_vamsi@my-vm-instance
      - --zone=asia-east1-b
      - --project=enhub-cloud-interns
      - --command=sudo apt-get update && sudo apt-get install -y unzip curl python3

  # Step 6: Download the zip from GCS inside VM
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - compute
      - ssh
      - sajja_vamsi@my-vm-instance
      - --zone=asia-east1-b
      - --project=enhub-cloud-interns
      - --command=gsutil cp gs://vamsi-artifact-bucket/my-app.zip ~/my-app.zip

  # Step 7: Unzip and run the app inside VM
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - compute
      - ssh
      - sajja_vamsi@my-vm-instance
      - --zone=asia-east1-b
      - --project=enhub-cloud-interns
      - --command=unzip -o ~/my-app.zip -d ~/my-app && cd ~/my-app && nohup python3 app.py > output.log 2>&1 &

images:
  - 'gcr.io/cloud-builders/gcloud'

options:
  logging: CLOUD_LOGGING_ONLY
