steps:
  - name: 'gcr.io/cloud-builders/curl'
    id: 'Download ZIP from GitHub'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Starting download from GitHub..."
        curl -L -o source.zip https://github.com/20481A04K2/cloudbuildzipfile/archive/refs/heads/main.zip
        echo "Download completed"

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Show ZIP File Size'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "The size of the downloaded ZIP file:"
        ls -lh source.zip

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Get Access Token'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        ACCESS_TOKEN=$(gcloud auth print-access-token)
        echo $ACCESS_TOKEN > /workspace/token.txt
        echo "Access token saved"

  - name: 'gcr.io/cloud-builders/curl'
    id: 'Upload to Artifact Registry using curl'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        ACCESS_TOKEN=$(cat /workspace/token.txt)
        echo "Uploading ZIP to Artifact Registry with curl..."
        curl -X POST \
          -H "Authorization: Bearer $ACCESS_TOKEN" \
          -H "Content-Type: application/zip" \
          --data-binary "@source.zip" \
          "https://artifactregistry.googleapis.com/v1/projects/enhub-cloud-interns/locations/asia-east1/repositories/vamsi-generic-repo/packages/source-package/versions/1.0.0:upload"
        echo "Upload completed"

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Log to Cloud Logging'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud logging write cloudbuild-log "Cloud Build steps completed for source-package 1.0.0" --severity=INFO
