steps:
  - name: 'gcr.io/cloud-builders/curl'
    id: 'Download ZIP from GitHub'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - |
        echo "Starting download from GitHub..."
        curl -L https://github.com/your-username/your-repo/archive/refs/heads/main.zip -o source.zip
        echo "Download completed"

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Show ZIP File Size'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - |
        echo "The size of the downloaded ZIP file:"
        du -sh source.zip

  - name: 'gcr.io/cloud-builders/curl'
    id: 'Upload to Artifact Registry via CURL'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - |
        echo "Uploading ZIP to Artifact Registry using CURL..."
        curl -X POST \
          -H "Authorization: Bearer $(gcloud auth print-access-token)" \
          -H "Content-Type: application/zip" \
          --data-binary "@source.zip" \
          "https://asia-east1-artifactregistry.googleapis.com/v1/projects/enhub-cloud-interns/locations/asia-east1/repositories/vamsi-generic-repo/packages/source-package/versions?versionId=1.0.0"
        echo "Upload completed"

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
