steps:
  - name: 'gcr.io/cloud-builders/curl'
    id: 'Download ZIP from GitHub'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Downloading ZIP..."
        curl -L -o source.zip https://github.com/20481A04K2/cloudbuildzipfile/archive/refs/heads/main.zip
        echo "Downloaded ZIP file size:"
        ls -lh source.zip

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Get Access Token'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud auth print-access-token > /workspace/token.txt

  - name: 'gcr.io/cloud-builders/curl'
    id: 'Upload ZIP to Artifact Registry'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        ACCESS_TOKEN=$(cat /workspace/token.txt)
        echo "Uploading ZIP using curl..."
        curl -X POST \
          -H "Authorization: Bearer $ACCESS_TOKEN" \
          -H "Content-Type: application/zip" \
          --data-binary "@source.zip" \
          "https://artifactregistry.googleapis.com/v1/projects/enhub-cloud-interns/locations/asia-east1/repositories/vamsi-generic-repo/packages/source-package/versions/1.0.0:upload"
        echo "Upload completed"

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
