steps:
  - name: 'gcr.io/cloud-builders/curl'
    id: 'Download ZIP from GitHub'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - |
        echo "Starting download from GitHub..."
        curl -L https://github.com/your-username/your-repo/archive/refs/heads/main.zip -o source.zip
        echo "Download completed"

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Authenticate'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - |
        echo "Authenticating with Google Cloud..."
        # If you need to download the service account key from a Cloud Storage bucket:
        # gsutil cp gs://<your-bucket>/<your-service-account-key.json> /workspace/enhub-cloud-interns-004fbd59b047.json
        gcloud auth activate-service-account --key-file=/workspace/enhub-cloud-interns-004fbd59b047.json
        echo "Authentication successful"

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Show ZIP File Size'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - |
        echo "The size of the downloaded ZIP file:"
        du -sh source.zip

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Upload to Artifact Registry'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - |
        echo "Uploading ZIP to Artifact Registry..."
        gcloud artifacts generic upload \
          --project="enhub-cloud-interns" \
          --location="asia-east1" \
          --repository="vamsi-generic-repo" \
          --package="source-package" \
          --version="1.0.0" \
          source.zip
        echo "Upload completed"

options:
  logging: CLOUD_LOGGING_ONLY
