steps:
  # Step 1: Zip the application
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y zip
        zip -r my-app.zip .

  # Step 2: Upload the ZIP to Artifact Registry (generic)
  - name: 'gcr.io/cloud-builders/curl'
    args:
      - '-X'
      - 'POST'
      - '-H'
      - 'Authorization: Bearer $(gcloud auth print-access-token)'
      - '-F'
      - 'file=@my-app.zip'
      - 'https://asia-east1-artifactregistry.googleapis.com/v1/projects/enhub-cloud-interns/locations/asia-east1/repositories/vamsi-generic-repo/files/my-app.zip'

  # Step 3: SSH into VM and download the ZIP using curl
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute ssh sajja_vamsi@my-vm-instance --zone=asia-east1-b --project=enhub-cloud-interns \
        --command="curl -o my-app.zip -H \"Authorization: Bearer \$(gcloud auth print-access-token)\" \
        https://asia-east1-artifactregistry.googleapis.com/v1/projects/enhub-cloud-interns/locations/asia-east1/repositories/vamsi-generic-repo/files/my-app.zip"

  # Step 4: SSH and unzip & run app
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - compute
      - ssh
      - sajja_vamsi@my-vm-instance
      - --zone=asia-east1-b
      - --project=enhub-cloud-interns
      - --command=unzip -o my-app.zip -d my-app && cd my-app && nohup python3 app.py > output.log 2>&1 &

options:
  logging: CLOUD_LOGGING_ONLY

