steps:
  # Step 1: Check/create Artifact Registry (generic type for zips)
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if ! gcloud artifacts repositories describe vamsi-generic-repo --location=asia-east1 --project=enhub-cloud-interns; then
          echo "Repository doesn't exist. Creating now."
          gcloud artifacts repositories create vamsi-generic-repo \
            --repository-format=generic \
            --location=asia-east1 \
            --project=enhub-cloud-interns
        else
          echo "Repository already exists."
        fi

  # Step 2: Zip the application source code
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y zip
        zip -r /workspace/my-app.zip .

  # Step 3: Upload the zip to Cloud Storage (use gsutil builder)
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - 'cp'
      - '/workspace/my-app.zip'
      - 'gs://vamsi-artifact-bucket/my-app.zip'

  # Step 4: Delete existing VM if exists
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Deleting VM if it exists..."
        gcloud compute instances delete my-vm-instance --zone=asia-east1-b --quiet || true

  # Step 5: Create new VM
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - compute
      - instances
      - create
      - my-vm-instance
      - --zone=asia-east1-b
      - --machine-type=e2-micro
      - --image-family=debian-11
      - --image-project=debian-cloud
      - --boot-disk-size=10GB
      - --tags=http-server,https-server
      - --scopes=https://www.googleapis.com/auth/cloud-platform
      - --service-account=1064351983714-compute@developer.gserviceaccount.com
      - --project=enhub-cloud-interns

  # Step 6: SSH into VM and install dependencies (curl, unzip, python3)
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - compute
      - ssh
      - sajja_vamsi@my-vm-instance
      - --zone=asia-east1-b
      - --project=enhub-cloud-interns
      - --command=sudo apt-get update && sudo apt-get install -y unzip curl python3

  # Step 7: Download the zip from Cloud Storage inside VM
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute ssh sajja_vamsi@my-vm-instance --zone=asia-east1-b --project=enhub-cloud-interns \
        --command="gsutil cp gs://vamsi-artifact-bucket/my-app.zip ~/my-app.zip"

  # Step 8: SSH and unzip & run app
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - compute
      - ssh
      - sajja_vamsi@my-vm-instance
      - --zone=asia-east1-b
      - --project=enhub-cloud-interns
      - --command=unzip -o ~/my-app.zip -d ~/my-app && cd ~/my-app && nohup python3 app.py > output.log 2>&1 &

images:
  - 'gcr.io/cloud-builders/gcloud'

options:
  logging: CLOUD_LOGGING_ONLY
