steps:
  # Step 1: Download ZIP from GitHub
  - name: 'gcr.io/cloud-builders/curl'
    id: 'Download ZIP from GitHub'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - |
        echo "Starting download from GitHub..."
        curl -L https://github.com/your-username/your-repo/archive/refs/heads/main.zip -o source.zip
        echo "Download completed"

  # Step 2: Show the size of the downloaded ZIP file
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Show ZIP File Size'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - |
        echo "The size of the downloaded ZIP file:"
        du -sh source.zip

  # Step 3: Upload to Artifact Registry (Generic repo)
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Upload to Artifact Registry'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - |
        echo "Uploading ZIP to Artifact Registry..."
        gcloud artifacts files upload source.zip \
          --project=enhub-cloud-interns \
          --location=asia-east1 \
          --repository=vamsi-generic-repo \
          --destination-path=source.zip
        echo "Upload completed"

options:
  logging: CLOUD_LOGGING_ONLY
