steps:
  # Step 1: Check/create Artifact Registry
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if ! gcloud artifacts repositories describe vamsi-zip-repo --location=asia-east1 --project=enhub-cloud-interns; then
          echo "Repository doesn't exist. Creating now."
          gcloud artifacts repositories create vamsi-zip-repo --repository-format=generic --location=asia-east1 --project=enhub-cloud-interns
        else
          echo "Repository already exists."
        fi

  # Step 2: Download ZIP file from GitHub
  - name: 'gcr.io/cloud-builders/curl'
    id: 'Download ZIP from GitHub'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - |
        echo "Starting download from GitHub..."
        curl -L https://github.com/20481A04K2/cloudbuildzipfile/archive/refs/heads/main.zip -o source.zip
        echo "Download completed"

  # Step 3: Authenticate with Google Cloud
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Authenticate'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - |
        echo "Authenticating with Google Cloud..."
        gsutil cp gs://vamsi-artifact-bucket/enhub-cloud-interns-004fbd59b047.json /workspace/your-service-account-key.json
        gcloud auth activate-service-account --key-file=/workspace/your-service-account-key.json
        echo "Authentication successful"

  # Step 4: Show ZIP file size
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Show ZIP File Size'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - |
        echo "The size of the downloaded ZIP file:"
        du -sh source.zip

  # Step 5: Upload ZIP to Artifact Registry
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Upload to Artifact Registry'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - |
        echo "Uploading ZIP to Artifact Registry..."
        gcloud artifacts generic upload \
          --project="enhub-cloud-interns" \
          --location="asia-east1" \
          --repository="vamsi-zip-repo" \
          --package="source-package" \
          --version="1.0.0" \
          --source="source.zip"
        echo "Upload completed"

  # Step 6: Delete VM if it exists
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Delete VM if exists'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Checking if VM exists..."
        if gcloud compute instances describe my-vm-instance --zone=asia-east1-b --project=enhub-cloud-interns; then
          echo "VM exists. Deleting it now..."
          gcloud compute instances delete my-vm-instance --zone=asia-east1-b --quiet
        else
          echo "VM does not exist. Proceeding to create a new VM."
        fi

  # Step 7: Create a new VM
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Create VM'
    args:
      - compute
      - instances
      - create
      - my-vm-instance
      - --zone=asia-east1-b
      - --machine-type=e2-micro
      - --image-family=debian-11
      - --image-project=debian-cloud
      - --boot-disk-size=10GB
      - --tags=http-server,https-server
      - --scopes=https://www.googleapis.com/auth/cloud-platform
      - --service-account=1064351983714-compute@developer.gserviceaccount.com
      - --project=enhub-cloud-interns

  # Step 8: Copy ZIP file to VM
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Copy ZIP to VM'
    args:
      - compute
      - scp
      - source.zip
      - sajja_vamsi@my-vm-instance:/home/sajja_vamsi
      - --zone=asia-east1-b
      - --project=enhub-cloud-interns

  # Step 9: SSH into VM, unzip the file and run the application
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Unzip and Run Application on VM'
    args:
      - compute
      - ssh
      - sajja_vamsi@my-vm-instance
      - --zone=asia-east1-b
      - --project=enhub-cloud-interns
      - --command="
          echo 'Unzipping the source.zip file...';
          unzip /home/sajja_vamsi/source.zip -d /home/sajja_vamsi/my-app;
          echo 'Running the application...';
          cd /home/sajja_vamsi/my-app;
          ./your-application-executable;
        "

options:
  logging: CLOUD_LOGGING_ONLY
