steps:
  # Step 1: Download ZIP from GitHub
  - name: 'gcr.io/cloud-builders/curl'
    args:
      - '-L'
      - 'https://github.com/your-username/your-repo/archive/refs/heads/main.zip'
      - '-o'
      - 'source.zip'

  # Step 2: Upload ZIP file to Artifact Registry
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'artifacts'
      - 'repositories'
      - 'upload'
      - '--project=enhub-cloud-interns'
      - '--location=asia-east1'
      - '--repository=vamsi-generic-repo'
      - '--package=my-app'
      - '--version=1.0.0'
      - '--file=source.zip'
